name: Terraform CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Terraform Init
        working-directory: Week1/terraform-vpc-module
        run: terraform init

      - name: Terraform Validate
        working-directory: Week1/terraform-vpc-module
        run: terraform validate

      - name: Terraform Plan
        working-directory: Week1/terraform-vpc-module
        run: terraform plan
